### ISSUE TITLE
The website and service seem to be broken

### ISSUE THREAD

**Issue by konrad-parada** [ethanzohar/discoverify#12]
When I go in the website it says as follows:
```
502 Bad Gateway
nginx/1.18.0 (Ubuntu)
```

I used the website for two days and after it stopped updating, I checked the website and it showed that error.

**Comment by ethanzohar** [comment]
Hey thanks for pointing this out! Turns out I ran out of storage space on the server. Problem should be fixed now and new playlists will come out once again tonight!

Thanks for bringing it to my attention <3
