### ISSUE TITLE
where do I find the created playlist?

### ISSUE THREAD

**Issue by StefanL38** [ethanzohar/discoverify#13]
Hi, 
I am a german user of Spotify family premium abonnenment.
I logged in to your service and made adjustments to my preferences.

I got the message
Your playlist was last updated 3 minutes ago
You can find your new playlist in Spotify under the title **Discover Daily**
We will update the songs in your playlist every 24 hours!

But I **can't** find this Discover Daily thing
Where do I find it? 
Is this a playlist?
what sub-sub-sub-menu inside the android spotify app do I have to "tap-down" to find it?
could it be that the mix of the week gets updated daily now but the name is still mix of the week?
Is your service terminated by spotify?
no idea why it is not working

**Comment by ethanzohar** [comment]
You should be able to find it in your Spotify library. The playlist will be called `Discover Daily`

Here is an example of what it will look like (I just generated a new playlist for myself, hence the date added being 1 minute ago):
![image](https://github.com/ethanzohar/discoverify/assets/32753718/0435e5df-017a-41be-9b2b-6a9230c7d10d)
