### ISSUE TITLE
Double billed

### ISSUE THREAD

**Issue by yagasoft** [ethanzohar/discoverify#22]
Hello,

Sorry to post this here; I couldn't find a support email or interface on your website.

I have been subscribed for a while. This month I was double billed for some reason as shown below.

On stripe, I am billed once though.

Bank message
![image](https://github.com/user-attachments/assets/61419331-35f7-4436-9ae7-2ff1f5ddd10c)

Stripe invoices
![image](https://github.com/user-attachments/assets/3017cfa6-723b-4345-a240-e2fe937c23e2)

**Comment by ethanzohar** [comment]
Hey @yagasoft I am really sorry to hear this. Could you send an email to ethanzohar9@gmail.com with the email that you signed up to Discoverify with and I can look into it for you right away!

**Comment by ethanzohar** [comment]
I have received your email, I'll close out this ticket and we can continue over email
